In [1]:
pip install numpy

     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ---------------------------------------- 61.0/61.0 kB 3.4 MB/s eta 0:00:00
   ---------------------------------------- 0.0/15.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/15.5 MB 1.5 MB/s eta 0:00:11
   ---------------------------------------- 0.1/15.5 MB 1.7 MB/s eta 0:00:10
    --------------------------------------- 0.3/15.5 MB 1.9 MB/s eta 0:00:09
    --------------------------------------- 0.4/15.5 MB 1.9 MB/s eta 0:00:09
   - -------------------------------------- 0.5/15.5 MB 1.8 MB/s eta 0:00:09
   - -------------------------------------- 0.5/15.5 MB 1.9 MB/s eta 0:00:09
   - -------------------------------------- 0.8/15.5 MB 2.2 MB/s eta 0:00:07
   -- ------------------------------------- 0.8/15.5 MB 2.2 MB/s eta 0:00:07
   -- ------------------------------------- 0.9/15.5 MB 2.2 MB/s eta 0:00:07
   -- ------------------------------------- 1.1/15.5 MB 2.3 MB/s eta 0:00:07
   -- --

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [6]:
# perkalian matriks array

import numpy as np

a = np.array([[[2,6], [9,3],[7,5]]])
b = np.array([[[8,4], [4,2], [1,3]]])

kali = a*b
print(kali)

[[[16 24]
  [36  6]
  [ 7 15]]]


In [8]:
# pengurangan matriks array

import numpy as np

a = np.array([[[8,6], [9,3],[7,5]]])
b = np.array([[[6,4], [4,2], [1,3]]])

kurang = a-b
print(kurang)

[[[2 2]
  [5 1]
  [6 2]]]


In [21]:
# transpose matriks array

import numpy as np

a = np.array([[8,6,7], [9,3,4], [5,9,8]])
b = np.array([[6,4,7], [4,2,5], [1,3,3]])

transpose_a = np.transpose (a)
transpose_b = np.transpose (b)
print (transpose_a)
print ( transpose_b)

[[8 9 5]
 [6 3 9]
 [7 4 8]]
[[6 4 1]
 [4 2 3]
 [7 5 3]]


In [41]:
# inverse matriks array

import numpy as np

a = np.array([[1,2], [9,3]])
b = np.array([[7,4], [ 6,3]])

inverse_a = np.linalg.inv(a)
inverse_b = np.linalg.inv(b)
print("\nInverse matrkis a:")
print(inverse_a)
print("\nInverse matrkis b:")
print(inverse_b)




Inverse matrkis a:
[[-0.2         0.13333333]
 [ 0.6        -0.06666667]]

Inverse matrkis b:
[[-1.          1.33333333]
 [ 2.         -2.33333333]]


In [39]:
# determinan matriks array

import numpy as np

a = np.array([[8,2], [6,9]])
b = np.array([[2,5], [ 4,2]])

determinan_a = np.linalg.det(a)
determinan_b = np.linalg.det(b)
print("Determinan dari matriks a:", determinan_a) 
print("Determinan dari matriks b:", determinan_b)

Determinan dari matriks a: 59.999999999999986
Determinan dari matriks b: -15.999999999999998
